<a href="https://colab.research.google.com/github/lmly303/Numpy/blob/main/np1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Creating array from list**

In [4]:
arr_1d = np.array([1,2,3,4])
print("1d array : ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array : ", arr_2d)


1d array :  [1 2 3 4]
2d array :  [[1 2 3]
 [4 5 6]]


**List vs numpy array**

In [3]:
py_list = [1,2,3] # write the array the no. of times [1,2,3,1,2,3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1,2,3]) # element wise multiplication [2,4,6]
print("Numpy array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Numpy array multiplication  [2 4 6]

 List operation time:  0.0742800235748291

 Numpy operation time:  0.0234527587890625


**Creating array from scratch**

In [23]:
zero = np.zeros((2,3))
print("zero array :",zero)

one = np.ones((2,2))
print("one array :",one)

full = np.full((2,2),7)
print("full array :",full)

random = np.random.random((2,2))
print("random array :",random)

sequence = np.arange(0,10,2)
print("sequence array :",sequence)


zero array : [[0. 0. 0.]
 [0. 0. 0.]]
one array : [[1. 1.]
 [1. 1.]]
full array : [[7 7]
 [7 7]]
random array : [[0.69524775 0.26129546]
 [0.19501702 0.041386  ]]
sequence array : [0 2 4 6 8]


**Vector, Matrix and Tensor**

In [9]:
vector = np.array([1,2,3])
print("vector : ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix : ", matrix)

tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("tensor : ", tensor)

vector :  [1 2 3]
matrix :  [[1 2 3]
 [4 5 6]]
tensor :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**Array Properties**

In [24]:
array = np.array([[1,2,3],[4,5,6]])
print("shape of array : ", array)
print("size of array : ", array.size)
print("dimension of array : ", array.ndim)
print("data type of array : ", array.dtype)

shape of array :  [[1 2 3]
 [4 5 6]]
size of array :  6
dimension of array :  2
data type of array :  int64


**Array Reshaping**

In [17]:
array = np.arange(12)
print("original array : ",array)

reshaped = array.reshape((3,4))
print("reshaped array : ",reshaped)

flatened = reshaped.flatten() # returns a copy
print("flatened array : ",flatened)

revaled = reshaped.ravel() # returns a view insted of a copy
print("revaled array : ",revaled)


#transpose
transpose = reshaped.T
print("transpose array : ",transpose)

original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
revaled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [19]:
array = np.array([1,2, True])
print(array)

[1 2 1]
