<a href="https://colab.research.google.com/github/lmly303/Numpy/blob/main/np2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Numpy array operations 1D array**

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing", arr[1:5])
print("with step", arr[1:8:2])
print("negative indexing", arr[5])

Basic slicing [2 3 4 5]
with step [2 4 6 8]
negative indexing 6


**2D Array**

In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("specific element", arr_2d[2,1])
print("entire row", arr_2d[1,:], arr_2d[2])
print("entire column", arr_2d[:,1])

specific element 8
entire row [4 5 6] [7 8 9]
entire column [2 5 8]


**Sorting**

In [5]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("sorted array", np.sort(arr_2d_unsorted, axis=0)) # sort in column
print("sorted array", np.sort(arr_2d_unsorted, axis=1)) # sort in row

sorted array [1 1 2 3 4 5 6 9]
sorted array [[1 1]
 [2 2]
 [3 3]]
sorted array [[1 3]
 [1 2]
 [2 3]]


**Filter**

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers %2==0]
print("Even numbers : ", even_numbers)

Even numbers :  [ 2  4  6  8 10]


**Filter with marks**

In [7]:
mask=numbers>5;
print(numbers[mask])

[ 6  7  8  9 10]


**Fancy indexing vs np.where**

In [12]:
indices=[2,4,6,8]
print("Fancy indexing : ", numbers[indices])

where_result = np.where(numbers>5)
print("Np where : ", numbers[where_result])
print(where_result)

Fancy indexing :  [3 5 7 9]
Np where :  [ 6  7  8  9 10]
(array([5, 6, 7, 8, 9]),)


In [15]:
condition_array = np.where(numbers>5, True, False) # its life if else condition
print(condition_array)
condition_array2 = np.where(numbers>5, numbers*2, numbers) # agar true ahi toh multiply by 2 warna same number
print(condition_array2)

[False False False False False  True  True  True  True  True]
[ 1  2  3  4  5 12 14 16 18 20]


**Adding and removing Data**

In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)
print(arr1+arr2) # indexing k basis pr values add kardi


[1 2 3 4 5 6]
[5 7 9]


**Array Compatibility**

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("Compatibility Shapes : ", a.shape == b.shape)
print("Compatibility Shapes : ", a.shape == c.shape)

Compatibility Shapes :  True
Compatibility Shapes :  False


In [22]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original,new_row)) # vstack hamesha row add karta hai
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col)) # hstack se column add hota hai
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


**Deleteing from an array**

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
deleted = np.delete(arr, 2) # index dena hota hai
print("Array after deletion: ", deleted)

deleted2 = np.delete(arr, (2,4)) # index dena hota hai
print("Array after deletion: ", deleted2)


Array after deletion:  [1 2 4 5 6 7 8]
Array after deletion:  [1 2 4 6 7 8]
