<a href="https://colab.research.google.com/github/lmly303/Numpy/blob/main/np3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("=== Zomato sales analysis ===")
print("shape of the data : ", sales_data.shape)
print("first 3 restraunt data : ", sales_data[0:3])

=== Zomato sales analysis ===
shape of the data :  (5, 5)
first 3 restraunt data :  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [12]:
# total sales per year
print(np.sum(sales_data, axis=0))

# yearly total
yearly_total = np.sum(sales_data[:, 1:],axis=0)
print(yearly_total)

# min sales per restraunt
min_sales = np.min(sales_data[:, 1:], axis=1)
print(min_sales)

# average sales per restraunt
avg_sales = np.mean(sales_data[:, 1:],axis=1)
print(avg_sales)

# max sales per restraunt
max_sales = np.max(sales_data[:, 1:], axis=0)
print(max_sales)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[150000 120000 200000 180000 160000]
[200000. 152500. 247500. 225000. 195000.]
[200000 230000 260000 300000]


In [15]:
# cumulitive sum 1, 2, 3 = 1, 3, 6
cum_sales = np.cumsum(sales_data[:, 1:], axis=1)
print(cum_sales)

plt.figure(figsize=(10,6))
# figure(): This function creates a new figure (i.e., a blank canvas for plotting).
# figsize=(10,6): This sets the size of the figure in inches:
# 10 inches wide
# 6 inches tall
plt.plot(np.mean(cum_sales, axis=0))
plt.title("average cumulative sales across all restraunts")
plt.xlabel("years")
plt.ylabel("sales")
plt.grid(True)
plt.show()

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [17]:
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])

print("Vector addition: ", vector1 + vector2)

print("\n Multiplication vector", vector1 * vector2)

print("\nDot Product", np.dot(vector1, vector2)) # (1⋅6)+(2⋅7)+(3⋅8)+(4⋅9)+(5⋅10) = 6+14+24+36+50 = 130
​



Vector addition:  [ 7  9 11 13 15]

 Multiplication vector [ 6 14 24 36 50]

Dot Product 130


In [18]:
restaurant_types = np.array(['biryani', 'chinese', 'pizza', 'burger', 'cafe'])
vectorized_upper = np.vectorize(str.upper)
print("Vectorized Upper", vectorized_upper(restaurant_types))

Vectorized Upper ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


In [19]:
monthly_avg = sales_data[:, 1:] / 12

print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]


In [ ]:
S